### ISSUE TITLE
Asking About Code Release Date

### ISSUE THREAD

**Issue by Njasa2k** [kfirgoldberg/ConceptLab#1]
Hi there,

I read your paper on "ConceptLab" for making unique images. Exciting stuff! I checked your GitHub but couldn't find the code. Any idea when you'll be sharing it? Can't wait to try it out.

**Comment by MrXwu** [comment]
Hi there,

I read your paper on "ConceptLab" for making unique images. Exciting stuff! I checked your GitHub but couldn't find the code. Any idea when you'll be sharing it? Can't wait to try it out.

**Comment by eladrich** [comment]
Code is now available 🧑‍💻
