### ISSUE TITLE
Can conceptlabs mix styles in Evolutionary Creative Generation?

### ISSUE THREAD

**Issue by TruthSearcher** [kfirgoldberg/ConceptLab#2]
title

**Comment by eladrich** [comment]
Can you elaborate?

**Comment by TruthSearcher** [comment]
similar to how you can mix content
![image](https://github.com/kfirgoldberg/ConceptLab/assets/134135767/6373a9a9-76e0-478c-9138-c6c201479ba8)
can it be done to style?

**Comment by eladrich** [comment]
Potentially yes, just choose a set of images for each `parent` that represents the corresponding style. These images can come either from some style you generated with `ConceptLab` or from existing style images that you have

Let us know how it goes 😊
