### ISSUE TITLE
Is this only available for Kandinsky?

### ISSUE THREAD

**Issue by olliacc** [kfirgoldberg/ConceptLab#3]
Is this only available for Kandinsky and not any of the stable Diffusion models?

**Comment by eladrich** [comment]
Yep, the optimization process is dependent on the diffusion prior model used by Kandinsky.
You can however try and replace the Unet part with Stable Diffusion by using something like IPAdapter, see this demo for example
https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter_t2i_demo.ipynb
